version: 0.0
os: linux
files:
  - source: /index.js
    destination: /var/www/html/upworktest/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  AfterInstall:
    - zip -r myapp.zip *
    - cp myapp.zip /var/www/html/upworktest/
    - location: scripts/after_install
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root