#!/bin/bash
#service httpd start
#cp -r * /var/www/html/upworktest/
rm -rf /var/www/html/upworktest/
git clone https://github.com/manish8561/aws.git /var/www/html/upworktest/
cd /var/www/html/upworktest
npm i
echo coping the files